spring:
  application:
    name: symbol-service
  datasource:
    url: jdbc:mysql://localhost:3306/symbol_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
